#ifndef ENVIRONMENT_API_ENDPOINTS_H
#define ENVIRONMENT_API_ENDPOINTS_H

#define CLEAR_SCREEN_ENDPOINT 1

#define PRINT_STRING_ENDPOINT 100
#define PRINT_CHAR_ENDPOINT 101

#define ENABLE_BACKGROUND_AUDIO_ENDPOINT 500
#define DISABLE_BACKGROUND_AUDIO_ENDPOINT 501
#endif