#ifndef HANDLER_IDS_H
#define HANDLER_IDS_H

#define KEY_HANDLER 0
#define TICK_HANDLER 1
#define RTC_HANDLER 2
#define RESTORE_CONTEXT_HANDLER 3
#define USER_ENVIRONMENT_API_HANDLER 4
#define EXCEPTION_HANDLER 5
#define REGISTERS_HANDLER 6

#endif
