#ifndef SYSCALL_CODES_H
#define SYSCALL_CODES_H


// 0 - 999 reserved for SYSTEM syscalls
#define SET_HANDLER_SYSCALL 0
#define RUN_PROGRAM_SYSCALL 1
#define QUIT_PROGRAM_SYSCALL 2
#define USER_ENVIRONMENT_API_SYSCALL 3
#define SLEEP_SYSCALL 4
#define SET_SYSTEM_STACK_BASE_SYSCALL 5

// 1000 - 1999 reserved for DRIVER syscalls

// 1000 - 1099 reserved for VIDEO DRIVER syscalls
#define DRAW_PIXEL_SYSCALL 1000
#define DRAW_RECTANGLE_SYSCALL 1001
#define DRAW_RECTANGLE_BORDER_SYSCALL 1002

#define DRAW_CHAR_SYSCALL 1010
#define DRAW_STRING_SYSCALL 1011
#define DRAW_CHAR_AT_SYSCALL 1012
#define DRAW_STRING_AT_SYSCALL 1013
#define DRAW_NUMBER_SYSCALL 1014
#define DRAW_NUMBER_AT_SYSCALL 1015
#define DRAW_HEX_SYSCALL 1016
#define DRAW_HEX_AT_SYSCALL 1017

// #define DRAW_BITMAP_SYSCALL 1020

#define IS_CURSOR_IN_BOUNDARIES_SYSCALL 1030
#define SET_CURSOR_COL_SYSCALL 1031
#define SET_CURSOR_LINE_SYSCALL 1032
#define GET_CURSOR_COL_SYSCALL 1033
#define GET_CURSOR_LINE_SYSCALL 1034

#define CLEAR_SCREEN_SYSCALL 1040
#define SET_FONT_SIZE_SYSCALL 1050
#define SET_FONT_SYSCALL 1051

#endif