#ifndef SYSCALL_CODES_H
#define SYSCALL_CODES_H


// 0 - 999 reserved for SYSTEM syscalls
#define SET_HANDLER_SYSCALL 0
#define RUN_PROGRAM_SYSCALL 1
#define QUIT_PROGRAM_SYSCALL 2
#define USER_ENVIRONMENT_API_SYSCALL 3

// 1000 - 1999 reserved for DRIVER syscalls

// 1000 - 1099 reserved for VIDEO DRIVER syscalls
#define DRAW_PIXEL_SYSCALL 1000
// #define DRAW_RECT_SYSCALL 1001 etc
#define DRAW_CHAR_SYSCALL 1010
#define DRAW_STRING_SYSCALL 1011
#define DRAW_CHAR_AT_SYSCALL 1012
#define DRAW_STRING_AT_SYSCALL 1013
#define CLEAR_SCREEN_SYSCALL 1020
#define SET_CURSOR_COL_SYSCALL 1021
#define SET_CURSOR_LINE_SYSCALL 1022
#define GET_CURSOR_COL_SYSCALL 1023
#define GET_CURSOR_LINE_SYSCALL 1024

#endif